# Generated by Django 5.1.6 on 2025-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.CharField(default=2000, max_length=4),
            preserve_default=False,
        ),
    ]
